// useStyles

import {
  agTextColorStyle,
  borderStyle,
  screenBackgroundStyle,
} from "@/constants/Styles";
import { useAllColors } from "./useAllColors";

const useStyles = () => {
  const {
    screenBackground,
    agGray100,
    agGray200,
    agGray400,
    agGray500,
    agGray600,
    agGray800,
    agGray900,
    agPrimary,
    agPrimaryLight,
    agGray300,
    agGray700,
    agLightActive,
    textLight,
    agSuccess,
    agSuccessLight,
    agDanger,
    agDangerLight,
    agInfo,
    agInfoLight,
    agSecondary,
    agSecondaryLight,
    agWarning,
    agWarningLight,
  } = useAllColors();

  return {
    screenBackground: screenBackgroundStyle(screenBackground),
    agLightActive: screenBackgroundStyle(agLightActive).containerBacgkround,
    agBgDangerStyle: screenBackgroundStyle(agDanger).containerBacgkround,
    agBgDangerLightStyle:
      screenBackgroundStyle(agDangerLight).containerBacgkround,
    agBgSuccessStyle: screenBackgroundStyle(agSuccess).containerBacgkround,
    agBgSuccessLightStyle:
      screenBackgroundStyle(agSuccessLight).containerBacgkround,
    agBgPrimaryStyle: screenBackgroundStyle(agPrimary).containerBacgkround,
    agBgPrimaryLightStyle:
      screenBackgroundStyle(agPrimaryLight).containerBacgkround,
    agBgInfoStyle: screenBackgroundStyle(agInfo).containerBacgkround,
    agBgInfoLightStyle: screenBackgroundStyle(agInfoLight).containerBacgkround,
    agBgSecondaryStyle: screenBackgroundStyle(agSecondary).containerBacgkround,
    agBgSecondaryLightStyle:
      screenBackgroundStyle(agSecondaryLight).containerBacgkround,
    agBgWarningStyle: screenBackgroundStyle(agWarning).containerBacgkround,
    agBgWarningLightStyle:
      screenBackgroundStyle(agWarningLight).containerBacgkround,
    agBgGray100Style: screenBackgroundStyle(agGray100).containerBacgkround,
    agBgGray200Style: screenBackgroundStyle(agGray200).containerBacgkround,
    agBgGray300Style: screenBackgroundStyle(agGray300).containerBacgkround,
    agBgGray400Style: screenBackgroundStyle(agGray400).containerBacgkround,
    agBgGray500Style: screenBackgroundStyle(agGray500).containerBacgkround,
    agBgGray600Style: screenBackgroundStyle(agGray600).containerBacgkround,
    agBgGray700Style: screenBackgroundStyle(agGray700).containerBacgkround,
    agBgGray800Style: screenBackgroundStyle(agGray800).containerBacgkround,
    agBgGray900Style: screenBackgroundStyle(agGray900).containerBacgkround,
    agBorderGray300Style: borderStyle(agGray300).border,
    agBorderSuccessStyle: borderStyle(agSuccess).border,
    agBorderSuccessLightStyle: borderStyle(agSuccessLight).border,
    agBorderDangerStyle: borderStyle(agDanger).border,
    agBorderDangerLightStyle: borderStyle(agDangerLight).border,
    agBorderInfoStyle: borderStyle(agInfo).border,
    agBorderInfoLightStyle: borderStyle(agInfoLight).border,
    agBorderSecondaryStyle: borderStyle(agSecondary).border,
    agBorderSecondaryLightStyle: borderStyle(agSecondaryLight).border,
    agBorderWarningStyle: borderStyle(agWarning).border,
    agBorderWarningLightStyle: borderStyle(agWarningLight).border,
    agBorderGray600Style: borderStyle(agGray600).border,
    agBorderPrimaryStyle: borderStyle(agPrimary).border,
    agGray100Color: agTextColorStyle(agGray100).textColor,
    agGray200Color: agTextColorStyle(agGray200).textColor,
    agGray300Color: agTextColorStyle(agGray300).textColor,
    agGray400Color: agTextColorStyle(agGray400).textColor,
    agGray500Color: agTextColorStyle(agGray500).textColor,
    agGray600Color: agTextColorStyle(agGray600).textColor,
    agGray700Color: agTextColorStyle(agGray700).textColor,
    agGray800Color: agTextColorStyle(agGray800).textColor,
    agGray900Color: agTextColorStyle(agGray900).textColor,
    agPrimaryColor: agTextColorStyle(agPrimary).textColor,
    agBgDangerStyle: screenBackgroundStyle(agDanger).containerBacgkround,
    agTextLightStyle: agTextColorStyle(textLight).textColor,
    agTextSuccessStyle: agTextColorStyle(agSuccess).textColor,
    agTextSuccessLightStyle: agTextColorStyle(agSuccessLight).textColor,
    agTextDangerStyle: agTextColorStyle(agDanger).textColor,
    agTextDangerLightStyle: agTextColorStyle(agDangerLight).textColor,
    agTextInfoStyle: agTextColorStyle(agInfo).textColor,
    agTextInfoLightStyle: agTextColorStyle(agInfoLight).textColor,
    agTextSecondaryStyle: agTextColorStyle(agSecondary).textColor,
    agTextSecondaryLightStyle: agTextColorStyle(agSecondaryLight).textColor,
    agTextWarningStyle: agTextColorStyle(agWarning).textColor,
    agTextWarningLightStyle: agTextColorStyle(agWarningLight).textColor,
    agTextPrimaryStyle: agTextColorStyle(agPrimary).textColor,
  };
};
export default useStyles;
